PDF/Areas/PDF/Models/Document.cs
#region Usings

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#endregion

#nullable disable

namespace PDF.Models {

    public partial class Document {

        #region Model Attributes

        [NotMapped]
        [Display(Name = "File Name")]
        public string FileName { get; set; }

        #endregion

        #region Navigation Properties


        #endregion

    }

}

PDF/Areas/PDF/Controllers/DownloadController.cs
#region Usings

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MimeKit;
using Serilog;
using PDF.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Utilities;

#endregion

namespace PDF.Controllers {

    [Area("PDF")]
    [Authorize(Policy = "Administrators")]
    public class DownloadController : Controller {

        #region Properties and Variables

        private readonly IConfiguration Configuration;
        private readonly ILogger<DownloadController> Logger;

        #endregion

        #region Class Methods

        // Constructor
        public DownloadController(IConfiguration configuration, ILogger<DownloadController> logger) {
            Configuration = configuration;
            Logger = logger;
        }

        #endregion

        #region Controller Methods

        // Index (Get)
        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet]
        public IActionResult Index() {
            List<Document> files = new();
            try {
                string[] f = Directory.GetFiles(@Configuration["PDFSettings:DownloadStoragePath"], "*.docx");
                foreach (string file in f) {
                    files.Add(new Document { FileName = Path.GetFileName(file) });
                }
                files = files.OrderByDescending(x => x.FileName).ToList();
            } catch (Exception ex) {
                Logger.LogError(ex, ex.Message);
                Site.Messages.Enqueue(ex.Message);
            }
            return View(files);
        }

        // Help
        [HttpGet, HttpPost]
        [ApiExplorerSettings(IgnoreApi = true)]
        public IActionResult Help() {
            try {
                Log.Logger.ForContext("UserId", User.UserId()).Information($"View PDF Converter Download Help");
            } catch (Exception ex) {
                Site.Messages.Enqueue(ex.Message);
                Logger.LogError(ex, ex.Message);
            }
            return View();
        }

        // Stream (Post)
        [HttpGet, HttpPost]
        [ApiExplorerSettings(IgnoreApi = true)]
        public IActionResult Stream([FromBody] IList<Document> documents) {
            string path = @Configuration["PDFSettings:DownloadStoragePath"];
            string filePath = "";
            try {
                foreach (Document b in documents) {
                    Response.Headers.Clear();
                    filePath = $@"{path}{b.FileName}";
                    Response.Headers["Content-Disposition"] = @$"attachment;filename={filePath}";
                    return PhysicalFile(filePath, MimeTypes.GetMimeType(filePath), Path.GetFileName(filePath));
                }
            } catch (Exception ex) {
                Logger.LogError(ex, ex.Message);
                Site.Messages.Enqueue(ex.Message);
            }
            return Json(false);
        }

        #endregion

    }

}

PDF/Areas/PDF/Controllers/HomeController.cs
#region Usings

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PDF.Models;
using System.Diagnostics;

#endregion

namespace PDF.Controllers {

    [Area("PDF")]
    [Authorize(Policy = "Users")]
    public class HomeController : Controller {

        #region Properties

        private readonly ILogger<HomeController> _logger;

        #endregion

        #region Class Methods

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        #endregion

        #region Controller Actions

        public IActionResult Index() {
            return View();
        }

        #endregion

    }

}

PDF/Areas/PDF/Views/Download/Help.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
	Layout = "_Dashboard";
	string Title = "Download Help";
}
@section CSS {

}

@section Scripts {

}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>SQL Server Management Objects</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
						<li class="breadcrumb-item active">@Title</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<!-- Main content -->
	<section class="content">
		<partial name="_Messages" />

		<div class="callout callout-info">
			<h5><i class="fas fa-info"></i> Note:</h5>
			This page has been enhanced for printing. Click the print button at the bottom of the page to test.
		</div>

		<div class="row">
			<div class="col-lg-6">
				<div class="card card-primary">
					<div class="card-header border-0">
						<h3 class="card-title">@Title</h3>
						<div class="card-tools">
							<a asp-action="Index" class="btn btn-tool btn-sm">
								<i class="fas fa-xmark" title="Close"></i>
							</a>
						</div>
					</div>
					<div class="card-body">
						<p>From this page you can see a list of all the files that were created during each backup operation. Downloading them up to disk is fast and easy:</p>
						<ol>
							<li class="mb-2">Click on the name of each file you'd like to download.</li>
							<li class="mb-2">Navigate to the folder where you'd like the file to be stored and click OK'</li>
							<li class="mb-2">Wait for the download to complete, then proceed to the next file.</li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<!-- /.content-wrapper -->

PDF/Areas/PDF/Views/Download/Index.cshtml
@model IList<PDF.Models.Document>
@using PDF.Models
@{
    Layout = "_Dashboard";
    string Title = "PDF Download";
}
@section CSS {

}

@section Scripts {

    <script>

        function DownloadSelected() {
            try {
                var grid = document.getElementById("DownloadGrid").ej2_instances[0];
                var selected = grid.getSelectedRecords();
                $.ajax({
                    type: "POST",
                    url: "/PDF/Download/Stream",
                    xhrFields: {
                        responseType: "blob"
                    },
                    data: JSON.stringify(selected),
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        window.location = "/PDF/Download";
                    },
                    error: function (xhr, opt, err) {
                        alert('Error: ' + xhr.status + ' - ' + xhr.statusText + ' - ' + xhr.responseText);
                        console.log('Error: ' + xhr.status + ' - ' + xhr.statusText + ' - ' + xhr.responseText);
                    }
                });
            } catch (ex) {
                alert(ex);
            }
        }

        function ExportToExcel() {
            var gridObj = document.getElementById("DownloadGrid").ej2_instances[0];
            gridObj.excelExport();
        }

        function ExportToPDF() {
            var gridObj = document.getElementById("DownloadGrid").ej2_instances[0];
            gridObj.pdfExport();
        }

    </script>

}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@Title Manager</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item active">@Title Manager</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <partial name="_Messages" />
        <div class="card card-primary">
            <div class="card-header border-0">
                <h3 class="card-title">Select Files</h3>
                <div class="card-tools">
                    <button class="btn btn-tool btn-sm" onclick="DownloadSelected()">
                        <i class="fas fa-play" title="Run"></i>
                    </button>
                    <a asp-controller="Download" asp-action="Help" class="btn btn-tool btn-sm">
                        <i class="fas fa-question" title="Help"></i>
                    </a>
                    <a asp-action="Index" class="btn btn-tool btn-sm">
                        <i class="fas fa-xmark" title="Close"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                @if (Model.Count() == 0) {
                    <emptyresult icon="fa-solid fa-puzzle-piece"></emptyresult>
                } else {
                    <ejs-grid id="DownloadGrid" dataSource="@Model" allowExcelExport="true" allowPdfExport="true" allowPaging="true" allowSorting="true">
                        <e-grid-selectionsettings mode="Row"></e-grid-selectionsettings>
                        <e-grid-columns>
                            <e-grid-column field="FileName" headerText="File Name" textAlign="Left"></e-grid-column>
                        </e-grid-columns>
                    </ejs-grid>
                }
            </div>
        </div>
    </section>
    )
</div>
<!-- /.content-wrapper -->